config/routes.rb
Rails.application.routes.draw do

  resources :group_events do
    collection do
      post :publish_event
    end
  end
  resources :users

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :users do
        post :restore_user
      end
      resources :group_events do
        post :publish_event
      end
    end
  end

  root :to => "group_events#index"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :group_event
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group_event.rb
class GroupEvent < ApplicationRecord
    acts_as_paranoid

    enum status: [ :draft, :publish ]
    
    belongs_to :user
    has_one :address, dependent: :destroy
    accepts_nested_attributes_for :address, allow_destroy: true

    validates :name, presence: true
    validates :start_date, presence: true, if: :status_publish?
    validates :duration, presence: true, if: :status_publish?
    validates :description, presence: true, if: :status_publish?

    def get_coordinates group_event_obj
        results = Geocoder.search(group_event_obj.address)
        co_ordinates = {}
        co_ordinates[:lat] =  results.first.coordinates[0] unless results.empty?
        co_ordinates[:lng] = results.first.coordinates[1] unless results.empty?
        co_ordinates
    end

    def end_date
        (start_date.present? && duration.present?) ? start_date + duration.days : " "
    end

    def publish
        status = 1
        save!
    end

    def event_publish_able?
        name.present? &&
        start_date.present? && 
        duration.present? &&
        description.present? &&
        nested_attributes_options.keys.present?
    end

    def status_publish? 
        status == "publish"
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_many :group_events
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
end

app/controllers/api/v1/group_events_controller.rb
class Api::V1::GroupEventsController < ApplicationController
    skip_before_action :verify_authenticity_token
    def new
        # @group_event = GroupEvent.new
        @user = User.find_by(id: 1)
        @group_event = @user.group_events.new
        @address = @group_event.build_address

        render json: @address
    end

    def index
        @group_events = GroupEvent.all

        render json: @group_events
    end
    
    def create
        @user = User.find_by(id: 1)

        @group_event = @user.group_events.new(events_params)

        return render_errors('Failed to create Event!', :unprocessable_entity) unless @group_event.save
        
        render json: @group_event

    end

    def publish_event
        @group_event = GroupEvent.find_by(id: params[:event])

        render json: @group_event
    end

    def show
        @group_event = GroupEvent.find_by(id: params[:id])

        return render_errors('Event is not presetn with this id!', :unprocessable_entity) if @group_event.nil?

        render json: @group_event
    end

    def edit
        @group_event = GroupEvent.find_by(id: params[:id])

        return render_errors('Event is not presetn with this id!', :unprocessable_entity) if @group_event.nil?

        render json: @group_event
    end

    def update

        @group_event = GroupEvent.find(params[:id])
        @group_event.update_attributes! events_params

        return render_errors('Failed to update Event!', :unprocessable_entity) unless @group_event.update(events_params)
        render json: @group_event
    end

    def destroy
        @group_event = GroupEvent.find(params[:id])
        @group_event.destroy
      
        return render_errors('Failed to delete Event!', :unprocessable_entity) unless @group_event.destroy
        render json: @group_event
      end
    private
    def events_params
        params.require(:group_event)
        .permit(:name, :start_date, :duration, :description, address_attributes: [:country, :city, :state, :zip])
    end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
    def create
        @user = User.new(user_params)
        if @user.save
            render json: @user
        else
            render json: { alert: @user.errors, status: :internal_server_error }
        end
    end
    
    def index
        render json: User.all
    end

    def restore_user
        if @user.soft_restore
            render json: @user
        else
            render status: :internal_server_error, json: {
            message: 'Could not restore user!',
            }
        end
    end 

    def show
        render json: @user
    end

    private
        def user_params
            params.require(:user).permit(:id, :name, :email, :password)
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def render_errors(errors, status = :internal_server_error)
    render json: { errors: errors }, status: status
  end
end

app/controllers/group_events_controller.rb
class GroupEventsController < ApplicationController
    before_action :set_group_event, except: %i[new create index]
    def new
        # @group_event = GroupEvent.new
        @user = User.find_by(id: 1)
        @group_event = @user.group_events.new
        @address = @group_event.build_address
    end
    def index
        @group_events = GroupEvent.all
    end
    
    def create
        @user = User.find_by(id: 1)

        @group_event = @user.group_events.new(events_params)

        @group_event.status = @group_event.event_publish_able? ? 1 : 0

            respond_to do |format|
            if @group_event.save
                format.html { redirect_to @group_event, notice: 'Group Event was successfully created.' }
                format.json { render action: 'show', status: :created, location: @group_event }
            else
                format.html { render action: 'new' }
                format.json { render json: @group_event.errors, status: :unprocessable_entity }
            end
        end
    end

    def publish_event
        if @group_event.event_publish_able? 
            @group_event.publish!
            redirect_to group_events_path
        else
            redirect_to edit_group_event_path(@group_event)
        end
    end

    def show
    end

    def edit
    end

    def update        
        @group_event.update_attributes! events_params
        redirect_to root_path
    end

    def destroy
        @group_event.destroy
      
        redirect_to group_events_path
    end

    private

    def set_group_event
        @group_event = GroupEvent.find(params[:id])
    end
    def events_params
        params.require(:group_event)
        .permit(:name, :start_date, :duration, :description, address_attributes: [:country, :city, :state, :street, :zip])
    end
        
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_events_helper.rb
module GroupEventsHelper
    def date_format date
        date.present? ? date.strftime('%Y-%m-%d') : ''
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/group_events/_form.html.erb
  
  <%= form_for @group_event do |f| %>

    <div class="form-group">
      <%= f.label :name, "Group Name", class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
    
    <div class="form-group">
      <%= f.label :Description, class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= f.text_area :description, rows: 5, cols: 25, class: "form-control tinymce" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :start_date, 'Start Date', class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= f.date_field :start_date, class: "form-control" %>
      </div>
    </div>
    
    <div class="form-group">
      <%= f.label :Duration, class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= f.number_field :duration, class: "form-control" %>
      </div>
    </div>

    <%= f.fields_for :address do |address_fields| %>
      <div class="form-group">
        <%= address_fields.label :Country , class: "col-md-4 control-label"%>
        <div class="col-md-8">
          <%= address_fields.text_field :country, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= address_fields.label :City, class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= address_fields.text_field :city, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= address_fields.label :State, class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= address_fields.text_field :state, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= address_fields.label :zip, 'Zip code', class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= address_fields.text_field :zip, class: "form-control" %>
        </div>
      </div>

    <% end %>
    <div class="form-group">
      <div class="text-right d-flex justify-content-between">
        <%= f.submit :Submit, class: 'btn btn-success'%>
      </div>
    </div>

    <% if @group_event.errors.any? %>
      <div id="error_explanation">
       
        <ul>
          <% @group_event.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    
  <% end %>
  
  <%= tinymce %>

app/views/group_events/edit.html.erb
<div class="container">
    <div class="row ">
        <div class="offset-2 col-sm-10 col-md-10 col-lg-11" >
        <h3>Edit Group Event</h3>

        <%= render 'form' %>

        <%= link_to 'Back', group_events_path, class: "btn btn-inverse" %>
    </div>
  </div>
</div>

app/views/group_events/index.html.erb
<div class="container">
    <div class="row ">
        <div class="offset-2 col-sm-8 col-md-8 col-lg-8" >
            <h3 class="text-center" >Listing Group Events</h3>

            <%= link_to 'New Group Event', new_group_event_path, class: "btn btn-inverse btn-primary" %>
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">Name</th>
                  <th scope="col">Desription</th>
                  <th scope="col">Duration</th>
                  <th scope="col">Start Date</th>
                  <th scope="col">End Date</th>
                  <th></th>
                  <th></th>
                  <th></th>
                  <th></th>

                </tr>
              </thead>
              <tbody>

              <% @group_events.each do |group_event| %>
                <tr>
                  <td><%= group_event.name %></td>
                  <td><%= group_event.description.html_safe %></td>
                  <td><%= group_event.duration %></td>
                  <td><%= date_format(group_event.start_date)%></td>
                  <td><%= date_format(group_event.end_date) %></td>
                  <td><%= link_to 'Show', group_event_path(group_event), class: "btn btn-dark" %></td>
                  <td><%= link_to 'Edit', edit_group_event_path(group_event), class: "btn btn-warning" %></td>
                  <td><%= link_to 'Destroy', group_event_path(group_event), class: "btn btn-danger", 
                          method: :delete,
                          data: { confirm: 'Are you sure?' } %></td>
                  <%if group_event.draft?%>
                    <td><%= button_to 'Publish', publish_event_group_events_path(id: group_event), class: "btn btn-primary mt-2", method: :post %></td>
                    <%else%>
                    <td><span class= "btn btn-success">Published</span></td>
                  <%end%>

                </tr>
              <% end %>

              </tbody>


            </table>
    </div>
  </div>
</div>

app/views/group_events/new.html.erb
<div class="container">
    <div class="row mt-2">
        <div class="offset-2 col-sm-10 col-md-10 col-lg-11" >
            <h3>Create New Group Event</h3>
            <%= render 'form' %>
            <%= link_to 'Back', group_events_path, class: "btn btn-inverse" %>
        </div>
    </div>
</div>

app/views/group_events/show.html.erb
<div class="container">
    <div class="row ">
        <div class="offset-2 col-sm-10 col-md-10 col-lg-11" >
          <%if @group_event.draft? %>
            <%= button_to 'Publish', publish_event_group_events_path(id: @group_event), class: "btn btn-primary mt-2", method: :post %>
          <% end %>

          <p>
            <strong>Group Name:</strong>
            <%= @group_event.name %>
          </p>
          <p>
            <strong>Start Date:</strong>
            <%= @group_event.start_date %>
          </p>
          <p>
            <strong>Description:</strong>
            <%= @group_event.description.html_safe %>
          </p>
          <p>
            <strong>End Date:</strong>
            <%= @group_event.end_date %>
          </p>
          <p>
            <strong>Durantion:</strong>
            <%= @group_event.duration %>
          </p>

          <%= link_to 'Edit', edit_group_event_path(@group_event), class: "btn btn-inverse" %>
          <%= link_to 'Back', group_events_path, class: "btn btn-inverse" %>
     </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Exercise201104Bilal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>